name: Docker

on:
  workflow_call:


jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3

    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: program

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: marcosrodriguessilva
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: marcosrodriguessilva/go_ci:${{ github.ref_name }}

